### ISSUE TITLE
Feature: E2Eテスト実装によるVSCode拡張機能とGroovy LSPの統合動作検証

### ISSUE THREAD

**Issue by char5742** [char5742/groovy-lsp#53]
## 概要

Groovy LSPサーバーとVSCode拡張機能の実際の統合動作を検証するためのEnd-to-End（E2E）テストフレームワークを実装します。実際のGroovyプロジェクト（JavaメインコードとGroovy/Spockテストを含む）を使用して、LSPサーバーの全機能が正しく動作することを自動的に検証します。

## 背景・動機

現在、単体テストと統合テストは充実していますが、以下の観点でE2Eテストが必要です：

- VSCode拡張機能とLSPサーバー間の実際のプロトコル通信の検証
- 実際のGroovyプロジェクトでの動作確認（JavaとGroovyの混在環境）
- ユーザーが実際に体験するシナリオの自動テスト
- リグレッションの早期発見とCI/CDでの品質保証

### 1. テストフレームワーク

```
packages/e2e-tests/
├── src/
│   ├── test/
│   │   ├── e2e/
│   │   │   ├── CompletionE2ETest.ts        # 補完機能のE2Eテスト
│   │   │   ├── DiagnosticsE2ETest.ts       # 診断機能のE2Eテスト
│   │   │   ├── HoverE2ETest.ts             # ホバー機能のE2Eテスト
│   │   │   └── FormattingE2ETest.ts        # フォーマット機能のE2Eテスト
│   │   └── fixtures/
│   │       ├── sample-java-groovy-project/  # JavaメインコードとGroovy/Spockテスト
│   │       │   ├── src/main/java/          # Javaコード
│   │       │   ├── src/test/groovy/        # Spockテスト
│   │       │   └── build.gradle            # Gradleビルドファイル
│   │       └── sample-groovy-dsl-project/   # GroovyDSLプロジェクト
├── .vscode-test.js                          # VSCode Test設定
└── package.json
```

### 2. 技術スタック

- **@vscode/test-electron** - VSCode拡張機能のE2Eテストフレームワーク（最新推奨）
- **Mocha** - テストランナー
- **Chai** - アサーションライブラリ
- **Spock Framework** - Groovy側のテストフレームワーク

#### 基本機能テスト
- コード補完が正しく動作すること
- 診断メッセージが適切に表示されること
- ホバー情報が正確であること
- フォーマッティングが期待通りに動作すること

#### Java-Groovy統合テスト
- JavaクラスからGroovyクラスへの参照解決
- GroovyテストからJavaクラスへの参照解決
- Spockテストの特殊構文（given/when/then）の認識

#### パフォーマンステスト
- 大規模プロジェクトでの応答速度
- 初回起動時のインデックス作成時間

### 4. CI/CD統合

GitHub Actionsでの実行設定：

```yaml
name: E2E Tests
on: [push, pull_request]

jobs:
  e2e-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vscode-version: ['stable', 'insiders']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
      - run: npm ci
      - run: npm run compile
      - run: npm run test:e2e
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}
```

## 期待される効果

1. **品質保証の向上** - 実際の使用シナリオでの動作を自動検証
2. **リグレッション防止** - PRマージ前に統合動作を確認
3. **開発効率向上** - 手動テストの自動化
4. **ドキュメント効果** - E2Eテストがユースケースのドキュメントとして機能

## 実装ステップ

1. [ ] E2Eテストフレームワークのセットアップ（@vscode/test-electron）
2. [ ] サンプルGroovyプロジェクトの作成（Java+Groovy/Spock）
3. [ ] 基本機能のE2Eテスト実装（補完、診断、ホバー、フォーマット）
4. [ ] CI/CDパイプラインへの統合
5. [ ] パフォーマンステストの実装
6. [ ] ドキュメントの更新

## 参考資料

- [VS Code Extension Testing](https://code.visualstudio.com/api/working-with-extensions/testing-extension)
- [@vscode/test-electron Documentation](https://github.com/microsoft/vscode-test)
- [Language Server Protocol Testing Best Practices](https://microsoft.github.io/language-server-protocol/overviews/lsp/overview/)
